# Generated by Django 5.2 on 2025-04-22 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_clientuser_groups_clientuser_is_active_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='notifications_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
