# Generated by Django 5.2 on 2025-04-22 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_clientuser_notifications_enabled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientuser',
            name='phone_number',
        ),
    ]
