# Generated by Django 5.2 on 2025-04-23 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_clientuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='date_joined',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
