# Generated by Django 5.2 on 2025-04-24 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_clientuser_date_joined'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
