# Generated by Django 5.2 on 2025-04-24 01:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_clientuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientuser',
            name='status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Active', 'Active')], default='Pending', max_length=10),
        ),
    ]
