# Generated by Django 5.2 on 2025-04-13 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='organization',
            name='subdomain',
        ),
        migrations.AddField(
            model_name='organization',
            name='code',
            field=models.CharField(blank=True, max_length=6, unique=True),
        ),
    ]
