# Generated by Django 5.2 on 2025-04-16 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_remove_organization_subdomain_organization_code'),
    ]

    operations = [
        migrations.AddField(
            model_name='activationtoken',
            name='password',
            field=models.CharField(blank=True, max_length=128, null=True),
        ),
    ]
