# Generated by Django 5.2 on 2025-04-19 07:26

import booking.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('booking', '0001_initial'),
        ('organizations', '0003_activationtoken_password'),
        ('users', '0003_clientuser_groups_clientuser_is_active_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='employees', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='location',
            name='organization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='locations', to='organizations.organization'),
        ),
        migrations.AlterField(
            model_name='employee',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.clientuser'),
        ),
        migrations.AlterField(
            model_name='workspace',
            name='amenities',
            field=models.JSONField(blank=True, default=list, validators=[booking.models.validate_amenities]),
        ),
        migrations.DeleteModel(
            name='Organization',
        ),
    ]
