# Generated by Django 5.2 on 2025-04-21 17:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_clientuser_groups_clientuser_is_active_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sections', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Workspace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('type', models.CharField(choices=[('Desk', 'Desk'), ('Meeting Room', 'Meeting Room'), ('Private Office', 'Private Office'), ('Training Table', 'Training Table'), ('Others', 'Others')], max_length=50)),
                ('capacity', models.PositiveIntegerField()),
                ('description', models.TextField(blank=True, null=True)),
                ('amenities', models.JSONField(blank=True, default=list)),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='workspace.section')),
            ],
        ),
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.clientuser')),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='workspace.workspace')),
            ],
        ),
    ]
