<<<<<<< HEAD
# Generated by Django 5.2 on 2025-04-22 08:44
=======
# Generated by Django 5.2 on 2025-04-21 19:51
>>>>>>> d358c145d88ad1625741511a93deb7207ff00704

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
<<<<<<< HEAD
            field=models.CharField(choices=[('Desk', 'Desk'), ('Meeting Room', 'Meeting Room'), ('Private Office', 'Private Office'), ('Training Table', 'Training Table'), ('Others', 'Others')], max_length=50),
=======
            field=models.CharField(choices=[('Desk', 'Desk'), ('Room', 'Room'), ('Office', 'Office'), ('Hall', 'Hall'), ('Others', 'Others')], max_length=50),
>>>>>>> d358c145d88ad1625741511a93deb7207ff00704
        ),
    ]
