# Generated by Django 5.2 on 2025-04-21 19:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Desk', 'Desk'), ('Room', 'Room'), ('Office', 'Office'), ('Hall', 'Hall'), ('Others', 'Others')], max_length=50),
        ),
    ]
