# Generated by Django 5.2 on 2025-04-22 08:44

from django.db import migrations, models

class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(
                choices=[
                    ('Desk', 'Desk'),
                    ('Meeting Room', 'Meeting Room'),
                    ('Private Office', 'Private Office'),
                    ('Training Table', 'Training Table'),
                    ('Room', 'Room'),
                    ('Office', 'Office'),
                    ('Hall', 'Hall'),
                    ('Others', 'Others')
                ],
                max_length=50
            ),
        ),
    ]
