# Generated by Django 5.2 on 2025-04-21 23:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_activationtoken_password'),
        ('workspace', '0002_alter_workspace_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='section',
            name='organization',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sections', to='organizations.organization'),
        ),
    ]
