# Generated by Django 5.2 on 2025-04-21 23:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0003_section_organization'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workspace',
            name='section',
        ),
        migrations.DeleteModel(
            name='Section',
        ),
    ]
