# Generated by Django 5.2 on 2025-04-22 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0003_activationtoken_password'),
        ('workspace', '0004_remove_workspace_section_delete_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='workspace',
            name='organization',
            field=models.ForeignKey(default=547000, on_delete=django.db.models.deletion.CASCADE, related_name='workspaces', to='organizations.organization'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workspace',
            name='type',
            field=models.CharField(choices=[('Desk', 'Desk'), ('Room', 'Room'), ('Office', 'Office'), ('Hall', 'Hall'), ('Others', 'Others')], max_length=50),
        ),
    ]
