# Generated by Django 5.2 on 2025-04-23 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workspace', '0010_workspace_created_at_workspace_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workspace',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
